[package]
name = "ass_comp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assa_parse = { path = "../assa_parse" }
rust-bert = "0.21.0"
strsim = "0.10.0"
regex = "1.7.2"
